re-added upower option

diff --git a/battery b/battery
--- a/battery
+++ b/battery
@@ -6,7 +6,7 @@ battery: usage:
 
   general:
     -h, --help    print this message
-    -p            use pmset (more accurate)
+    -p            use program: pmset (Mac) or upower (Linux) (More accurate)
     -t            output tmux status bar format
     -a            output ascii bar instead of spark's
     -b            battery path            default: /sys/class/power_supply/BAT0
@@ -24,7 +24,7 @@ fi
 
 # For default behavior
 setDefaults() {
-  pmset_on=0
+  program_on=0
   output_tmux=0
   ascii=0
   ascii_bar='=========='
@@ -40,7 +40,7 @@ setDefaults
 battery_charge() {
     case $(uname -s) in
         "Darwin")
-            if ((pmset_on)) && hash pmset 2>/dev/null; then
+            if ((program_on)) && hash pmset 2>/dev/null; then
                 if [ "$(pmset -g batt | grep -o 'AC Power')" ]; then
                     BATT_CONNECTED=1
                 else
@@ -69,17 +69,30 @@ battery_charge() {
             fi
             ;;
         "Linux")
-			battery_state=$(cat $battery_path/status)
-			battery_full=$battery_path/charge_full
-			battery_current=$battery_path/charge_now
-            if [ $battery_state == 'Discharging' ]; then
-                BATT_CONNECTED=0
+            if [ -d $battery_path ]; then
+                batt_num=$(basename "$battery_path")
             else
-                BATT_CONNECTED=1
+                batt_num=$(ls /sys/class/power_supply | grep "BAT")
+                battery_path=/sys/class/power_supply/$batt_num
             fi
-			now=$(cat $battery_current)
-			full=$(cat $battery_full)
-			BATT_PCT=$((100 * $now / $full))
+
+            if ((program_on)) && hash upower 2>/dev/null; then
+                state=$(upower -i $(upower -e | grep "$batt_num") | grep "state:" | grep -o 'discharging\|charging\|fully-charged')
+                if [ $state == 'discharging' ]; then
+                    BATT_CONNECTED=0
+                else
+                    BATT_CONNECTED=1
+                fi
+                BATT_PCT=$(upower -i $(upower -e | grep BAT) | grep "percentage" | grep -o '[0-9]*%' | tr -d '%')
+            else
+                BATT_PCT=$(cat $battery_path/capacity)
+                battery_state=$(cat $battery_path/status)
+                if [ $battery_state == 'Discharging' ]; then
+                    BATT_CONNECTED=0
+                else
+                    BATT_CONNECTED=1
+                fi
+            fi
             ;;
     esac
 }
@@ -119,8 +132,8 @@ print_status() {
         GRAPH="⚡"
     else
         if hash spark 2>/dev/null; then
-			sparks=$(spark 0 ${BATT_PCT} 100)
-			GRAPH=${sparks:1:1}
+            sparks=$(spark 0 ${BATT_PCT} 100)
+            GRAPH=${sparks:1:1}
         else
             ascii=1
         fi
@@ -170,18 +183,18 @@ while getopts ":g:m:w:tab:p" opt; do
       ascii=1
       ;;
     p)
-      pmset_on=1
+      program_on=1
       ;;
     b)
-	  if [ -d $OPTARG ]; then
-		battery_path=$OPTARG
-	  else
-		>&2 echo "Battery not found, trying to use default path..."
-	    if [ ! -d $battery_path ]; then
-		  >&2 echo "Default battery path is also unreachable"
-		  exit 1
-		fi
-	  fi
+      if [ -d $OPTARG ]; then
+        battery_path=$OPTARG
+      else
+        >&2 echo "Battery not found, trying to use default path..."
+#        if [ ! -d $battery_path ]; then
+#          >&2 echo "Default battery path is also unreachable"
+#          exit 1
+#        fi
+      fi
       ;;
     \?)
       echo "Invalid option: -$OPTARG"
